ExtendedM.Enum = {
    BLIP_ICON = {
        GUN_SHOP = 110
    },

    KEYBIND = {
        E = 51
    },

    CONTROL = {
        LOOK_LR = 1,
        LOOK_UD = 2,
        LOOK_BEHIND = 3,
        LOOK_LEFT = 4,
        LOOK_RIGHT = 5,
        LOOK_DOWN = 6,
        ATTACK = 24,
        MOUSE_X = 239,
        MOUSE_Y = 240,
    },

    ITEM_TYPE = {
        VALUABLE = 1,
        VALUE_CONTAINER = 2,
        CONTRABAND = 3,
        UTILITY = 4,
        SYSTEM = 5
    },

    ITEM_RARITY = {
        TRASH = 1,
        COMMON = 2,
        UNCOMMON = 3,
        RARE = 4,
        VERY_RARE = 5
    },

    ITEM_ORIGIN = {
        DUMPSTER = 1,
        CRIMINAL = 2,
        DEALER = 3,
        COMMERICAL = 4,
        UNKNOWN = 5
    },

    CONTAINER_TYPE = {
        PLAYER = 1,
        BAG = 2,
        WAREHOUSE = 3,
        DEALER = 4,
        WORLD = 5,
        UNKNOWN = 6
    },

    -- this starts at 0 as it is an enum from gta.
    VEHICLE_MOD_PRICE_VARIATION = {
        MPV_STANDARD             = 0,
        MPV_SPORT                = 1,
        MPV_SUV                  = 2,
        MPV_SPECIAL              = 3,
        MPV_BIKE                 = 4,
        MPV_BTYPE3               = 5,
        MPV_SULTANRS             = 6,
        MPV_BANSHEE2             = 7,
        MPV_LURCHER_LIVERY       = 8,
        MPV_BTYPE2_LIVERY        = 9,
        MPV_VIRGO2               = 10,
        MPV_SLAMVAN3             = 11,
        MPV_FACTION3_WHEELS      = 12,
        MPV_OMNIS_LIVERY         = 13,
        MPV_BF400_LIVERY         = 14,
        MPV_TROPOS_LIVERY        = 15,
        MPV_BRIOSO_LIVERY        = 16,
        MPV_TROPHYTRUCK_LIVERY   = 17,
        MPV_TROPHYTRUCK2_LIVERY  = 18,
        MPV_CLIFFHANGER_LIVERY   = 19,
        MPV_TAMPA2_LIVERY        = 20,
        MPV_GARGOYLE_LIVERY      = 21,
        MPV_LE7B_LIVERY          = 22,
        MPV_TYRUS_LIVERY         = 23,
        MPV_LYNX_LIVERY          = 24,
        MPV_SHEAVA_LIVERY        = 25,
        MPV_IE_RETRO             = 26,
        MPV_IE_HIGH              = 27,
        MPV_IE_BIKE              = 28,
        MPV_GR_HEAVY             = 29,
        MPV_GR_LIGHT             = 30,
        MPV_GR_BIKE              = 31,
        MPV_GR_TRAILERLARGE      = 32,
        MPV_SMUG_STANDARD        = 33,
        MPV_SMUG_HEAVY           = 34,
        MPV_GANG_OPS_STANDARD    = 35,
        MPV_BATTLE_STANDARD      = 36,
        MPV_BATTLE_HEAVY         = 37,
        MPV_ARENA_WARS           = 38,
        MPV_RC_BANDITO           = 39,
    },

    -- this starts at 0 as it is an enum from gta.
    VEHICLE_MOD_MENU = {
        CMM_MAIN = 0, -- select mod or buy
        CMM_BUY = 1, -- select buy options
        CMM_MOD = 2, -- select mod options
        CMM_MAINTAIN = 3,
        CMM_ARMOUR = 4,
        CMM_BRAKES = 5,
        CMM_BODYWORK = 6,
        CMM_BULLBARS = 7,
        CMM_BUMPERS = 8,
        CMM_CHASSIS = 9,
        CMM_ENGINE = 10,
        CMM_ENGINEBAY = 11,
        CMM_EXHAUST = 12,
        CMM_EXPLOSIVES = 13,
        CMM_FAIRING = 14,
        CMM_FENDERS = 15,
        CMM_FRAME = 16,
        CMM_FRONTFORKS = 17,
        CMM_FRONTMUDGUARD = 18,
        CMM_FRONTSEAT = 19,
        CMM_FUELTANK = 20,
        CMM_GOLD_PREP = 21,
        CMM_GOLD_PREP2 = 22,
        CMM_GRILL = 23,
        CMM_HANDLEBARS = 24,
        CMM_HEADLIGHTS = 25,
        CMM_HOOD = 26,
        CMM_HORN = 27,
        CMM_LIGHTS = 28,
        CMM_LIGHTS_HEAD = 29,
        CMM_LIGHTS_NEON = 30,
        CMM_INSURANCE = 31, -- Now called LOSS/THEFT PREVENTION
        CMM_MIRRORS = 32,
        CMM_PLATES = 33,
        CMM_PLATEHOLDER = 34,
        CMM_PUSHBAR = 35,
        CMM_REARMUDGUARD = 36,
        CMM_REARSEAT = 37,
        CMM_PAINT_JOB = 38, -- Now called RESPRAY
        CMM_ROLLCAGE = 39,
        CMM_ROOF = 40,
        CMM_SADDLEBAGS = 41,
        CMM_SELL = 42,
        CMM_SIDESTEP = 43,
        CMM_SKIRTS = 44,
        CMM_SPAREWHEEL = 45,
        CMM_SPOILER = 46,
        CMM_SUSPENSION = 47,
        CMM_TAILGATE = 48,
        CMM_TRACKER = 49,
        CMM_TRANSMISSION = 50,
        CMM_TRUCKBED = 51,
        CMM_TRUNK = 52,
        CMM_TURBO = 53,
        CMM_VIN = 54,
        CMM_WHEELS_MAIN = 55,
        CMM_WHEELS = 56,
        CMM_WHEEL_COL = 57,
        CMM_WHEEL_ACCS = 58,
        CMM_WHEELIEBAR = 59,
        CMM_WINDOWS = 60,
        CMM_SUPERMOD = 61,
        CMM_SUPERMOD_PLTHOLDER = 62,
        CMM_SUPERMOD_PLTVANITY = 63,
        CMM_SUPERMOD_INTERIOR1 = 64,
        CMM_SUPERMOD_INTERIOR2 = 65,
        CMM_SUPERMOD_INTERIOR3 = 66,
        CMM_SUPERMOD_INTERIOR4 = 67,
        CMM_SUPERMOD_INTERIOR5 = 68,
        CMM_SUPERMOD_SEATS = 69,
        CMM_SUPERMOD_STEERING = 70,
        CMM_SUPERMOD_KNOB = 71,
        CMM_SUPERMOD_PLAQUE = 72,
        CMM_SUPERMOD_ICE = 73,
        CMM_SUPERMOD_TRUNK = 74,
        CMM_SUPERMOD_HYDRO = 75,
        CMM_SUPERMOD_ENGINEBAY1 = 76,
        CMM_SUPERMOD_ENGINEBAY2 = 77,
        CMM_SUPERMOD_ENGINEBAY3 = 78,
        CMM_SUPERMOD_CHASSIS2 = 79,
        CMM_SUPERMOD_CHASSIS3 = 80,
        CMM_SUPERMOD_CHASSIS4 = 81,
        CMM_SUPERMOD_CHASSIS5 = 82,
        CMM_SUPERMOD_DOOR_L = 83,
        CMM_SUPERMOD_DOOR_R = 84,
        CMM_SUPERMOD_LIVERY = 85,
        CMM_CHASSIS_GROUP = 86,
        CMM_INTERIOR_GROUP = 87,
        CMM_PLATE_GROUP = 88,
        CMM_ENGINE_GROUP = 89,
        CMM_DIALS = 90,
        CMM_TRIM = 91,
        CMM_LIGHT_COLOUR = 92,
        CMM_DEFLECTOR = 93,
        CMM_ORNAMENTS = 94,
        CMM_FENDERSTWO = 95,
        CMM_WAITING_ON_PLAYERS = 96,
        CMM_PRIMARY_COLOUR = 97,
        CMM_SECONDARY_COLOUR = 98,
        CMM_BUMPER_GROUP = 99,
        CMM_BUMPER_SUBMENU_GROUP = 100,
        CMM_HOOD_GROUP = 101,
        CMM_ROOF_GROUP = 102,
        CMM_SUPERMOD_TWO = 103
    },

    VEHICLE_MOD_TYPE = {
        MOD_SPOILER = 0,
        MOD_BUMPER_F = 1,
        MOD_BUMPER_R = 2,
        MOD_SKIRT = 3,
        MOD_EXHAUST = 4,
        MOD_CHASSIS = 5,
        MOD_GRILL = 6,
        MOD_BONNET = 7,
        MOD_WING_L = 8,
        MOD_WING_R = 9,
        MOD_ROOF = 10,
        
        MOD_ENGINE = 11,
        MOD_BRAKES = 12,
        MOD_GEARBOX = 13,
        MOD_HORN = 14,
        MOD_SUSPENSION = 15,
        MOD_ARMOUR = 16,
        
        MOD_TOGGLE_NITROUS = 17,
        MOD_TOGGLE_TURBO = 18,
        MOD_TOGGLE_SUBWOOFER = 10,
        MOD_TOGGLE_TYRE_SMOKE = 20,
        MOD_TOGGLE_HYDRAULICS = 21,
        MOD_TOGGLE_XENON_LIGHTS = 22,
        
        MOD_WHEELS = 23,
        MOD_REAR_WHEELS = 24,

        MOD_PLTHOLDER = 25,
        MOD_PLTVANITY = 26,
    
        MOD_INTERIOR1 = 27,
        MOD_INTERIOR2 = 28,
        MOD_INTERIOR3 = 29,
        MOD_INTERIOR4 = 30,
        MOD_INTERIOR5 = 31,
        MOD_SEATS = 32,
        MOD_STEERING = 33,
        MOD_KNOB = 34,
        MOD_PLAQUE = 35,
        MOD_ICE = 36,
    
        MOD_TRUNK = 37,
        MOD_HYDRO = 38,
    
        MOD_ENGINEBAY1 = 39,
        MOD_ENGINEBAY2 = 40,
        MOD_ENGINEBAY3 = 41,
    
        MOD_CHASSIS2 = 42,
        MOD_CHASSIS3 = 43,
        MOD_CHASSIS4 = 44,
        MOD_CHASSIS5 = 45,
    
        MOD_DOOR_L = 46,
        MOD_DOOR_R = 47,
    
        MOD_LIVERY = 48
    },

    VEHICLE_MOD_KIT_TYPE = {
        MKT_STANDARD = 0,
        MKT_SPORT = 1,
        MKT_SUV = 2,
        MKT_SPECIAL = 3
    }
}